### ISSUE TITLE
[bug]: Cannot select Accounts module under collection & collection files fields

### ISSUE THREAD

**Issue by shubham-pawar** [pkonetskiy/SuiteCRM_three_new_fields_types#5]
### Description:

When attempting to create collection or collection files, we cannot select Accounts module. 

### Steps to Reproduce:

Open the studio.
Navigate to the any module -> fields -> add fields.
Select data type collection or collection files.
Change module at select module dropdown, then you cannot go back to accounts module.

### Expected Behavior:

The users should be able to create these two fields for accounts module too.

### Actual Behavior:

The application module cannot be selected for these two fields in the studio.

### Screenshots/Logs:

<img width="229" alt="image" src="https://github.com/user-attachments/assets/6bd51e9a-15bd-45a4-8982-5037c4e970ce">

### Environment Details:

Operating System: Ubuntu 22.04
Browser/Version: Chrome
Version of the Repository: v1.0 alpha

**Comment by pkonetskiy** [comment]
I don't see a problem. For example, I can open the Contacts module in Studio and add a collection type field with the Accounts module. There is a pause before loading other field parameters.

**Comment by shubham-pawar** [comment]
Thank you for update!
